services:
  # on the rpi, we totally ignore the monitoring app kafdrop, we dont need it there to debug since its our prod env
  gateway_app:
    build:
      context: .
      dockerfile: Dockerfile.prod # Use Dockerfile.prod for production
    environment:
      NODE_ENV: production
    depends_on: !override
      - kafka
  kafka:
    image: guiters/kafka-armv7
  kafdrop: !reset
