name: CI - Builds & Starts the microservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # To be able to execute the jobs manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main
        clean: true
        fetch-depth: 0

    - name: Stop dependent Docker containers
      run: |
        echo "Stopping dependent containers..."
        docker stop sensors_app_prod plants_app_prod || echo "Containers not running or already stopped."

    - name: Stop and remove old gateway_app_prod container
      run: |
        docker rm -f gateway_app_prod || true

    - name: Remove old gateway-microservice-gateway_app_prod image
      run: |
        docker rmi -f gateway-microservice-gateway_app_prod || true

    - name: Build the Docker image and run the service
      run: |
        echo "Running the service..."
        chmod +x service-runner.sh
        ./service-runner.sh

    - name: Restart dependent Docker containers
      run: |
        echo "Restarting dependent containers..."
        docker start sensors_app_prod plants_app_prod || echo "Failed to restart one or more containers."
