name: CI - Builds & Starts the microservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # To be able to execute the jobs manually
  workflow_dispatch:
jobs:

  deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          ref: main
    - name: Build the Docker image
      run: docker compose up
